# Generated by Django 5.1.1 on 2024-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=255)),
                ('consumo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_de_calculo', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('emissao', models.FloatField()),
            ],
        ),
    ]
