# Generated by Django 5.1.1 on 2024-10-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='emissao',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
