# Generated by Django 5.1.1 on 2024-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbono', '0003_rename_carros_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_de_calcuo', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('emissao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=255)),
                ('consumo', models.FloatField()),
                ('emissao', models.FloatField()),
            ],
        ),
    ]
