# Generated by Django 5.1.1 on 2024-10-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbono', '0004_gas_onibus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gas',
            old_name='modo_de_calcuo',
            new_name='modo_de_calculo',
        ),
    ]
