# Generated by Django 5.1.1 on 2024-10-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbono', '0006_alter_gas_options_alter_onibus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onibus',
        ),
    ]
